import { 
  CustomerMaster, 
  VendorMaster, 
  ResourceMaster, 
  WorkPackageMaster, 
  UOMMaster, 
  TaxRuleMaster 
} from '../types/erp';

export const DEFAULT_CUSTOMERS: CustomerMaster[] = [
  {
    id: 'CUST-001',
    customerNo: 'CUST-1001',
    name: 'Vikram & Ananya Malhotra',
    companyName: 'Malhotra Living Trust',
    contactPerson: 'Vikram Malhotra',
    phone: '+91 98110 44219',
    email: 'vikram.malhotra@skyline.org',
    gstin: '07AAACM4412K1ZY',
    pan: 'AAACM4412K',
    billingAddress: 'Unit 1402, Tower 4, Skyline Residences, Golf Course Extension Road',
    city: 'Gurugram',
    state: 'Haryana',
    pincode: '122018',
    customerType: 'INDIVIDUAL_HOMEOWNER',
    creditLimit: 7500000,
    paymentTerms: 'Milestone Based (10% Adv, 30% Civil, 25% Joinery, 20% Finishes, 15% Handover)',
    status: 'ACTIVE',
    totalProjectsCount: 1,
    createdAt: '2026-02-15T10:00:00Z',
    notes: 'Premium 4BHK turnkey interior fit-out. High attention to soundproofing and Italian marble finish.'
  },
  {
    id: 'CUST-002',
    customerNo: 'CUST-1002',
    name: 'Dr. Sameer & Neha Sen',
    companyName: 'Sen Healthcare Consultants',
    contactPerson: 'Dr. Sameer Sen',
    phone: '+91 98712 90811',
    email: 'dr.sen@consultsen.in',
    gstin: '06AACCS7712P1ZX',
    pan: 'AACCS7712P',
    billingAddress: 'Villa 18, Palm Meadows, Whitefield',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560066',
    customerType: 'INDIVIDUAL_HOMEOWNER',
    creditLimit: 12000000,
    paymentTerms: 'Milestone Based (15% Adv, 35% Structural, 25% Millwork, 25% Handover)',
    status: 'ACTIVE',
    totalProjectsCount: 0,
    createdAt: '2026-03-01T11:30:00Z',
    notes: 'Luxury duplex renovation with custom home theater and smart KNX automation.'
  },
  {
    id: 'CUST-003',
    customerNo: 'CUST-1003',
    name: 'Nexus Techspaces LLP',
    companyName: 'Nexus Techspaces LLP',
    contactPerson: 'Rohit Khandelwal (VP Infrastructure)',
    phone: '+91 99100 23456',
    email: 'rohit.k@nexustechspaces.com',
    gstin: '29AAAFN9988H1ZU',
    pan: 'AAAFN9988H',
    billingAddress: 'Level 5, Tower B, Cyber City',
    city: 'Gurugram',
    state: 'Haryana',
    pincode: '122002',
    customerType: 'COMMERCIAL_ENTERPRISE',
    creditLimit: 25000000,
    paymentTerms: '30 Days Net on RA Bill Submission',
    status: 'ACTIVE',
    totalProjectsCount: 0,
    createdAt: '2026-03-10T14:00:00Z',
    notes: 'Grade-A office interior fit-out (8,500 sq.ft) with acoustic pods and open workstations.'
  }
];

export const DEFAULT_VENDORS: VendorMaster[] = [
  {
    id: 'VEND-001',
    vendorNo: 'VEND-2001',
    name: 'Saint-Gobain Glass & Glazing Solutions Ltd',
    tradeSpecialty: 'DOORS_WINDOWS_GLAZING',
    contactPerson: 'Manish Chawla',
    phone: '+91 98101 55432',
    email: 'm.chawla@saintgobain-partner.in',
    gstin: '07AAACS1122D1ZM',
    pan: 'AAACS1122D',
    address: 'Plot 44, Industrial Area Phase II',
    city: 'Okhla, New Delhi',
    rating: 5,
    bankAccountNumber: '9019283849102',
    bankIfsc: 'HDFC0000128',
    paymentTerms: '30 Days from delivery',
    complianceStatus: 'VERIFIED',
    leadTimeDays: 7,
    status: 'ACTIVE',
    notes: 'Exclusive supply partner for 10mm/12mm toughened frameless glass, mirrors & shower cubicles.'
  },
  {
    id: 'VEND-002',
    vendorNo: 'VEND-2002',
    name: 'Greenlam & Greenply Industries Depo',
    tradeSpecialty: 'CARPENTRY_JOINERY',
    contactPerson: 'Sunil Aggarwal',
    phone: '+91 98112 66781',
    email: 'sunil.ply@timbermarket.in',
    gstin: '07AABCG3344J1ZN',
    pan: 'AABCG3344J',
    address: 'Shop 12-14, Timber Market, Kirti Nagar',
    city: 'New Delhi',
    rating: 4.8,
    bankAccountNumber: '0029104000189',
    bankIfsc: 'ICIC0000029',
    paymentTerms: '15 Days Net',
    complianceStatus: 'VERIFIED',
    leadTimeDays: 3,
    status: 'ACTIVE',
    notes: 'Authorized distributor for IS:710 Marine Grade BWP Plywood, Birch Plywood & 1mm HD laminates.'
  },
  {
    id: 'VEND-003',
    vendorNo: 'VEND-2003',
    name: 'Havells & Schneider Modular Systems',
    tradeSpecialty: 'ELECTRICAL_AUTOMATION',
    contactPerson: 'Deepak Saxena',
    phone: '+91 98200 88912',
    email: 'sales@havellselectrical.in',
    gstin: '07AAACH5566K1ZP',
    pan: 'AAACH5566K',
    address: 'Sector 18, Udyog Vihar',
    city: 'Gurugram',
    rating: 4.7,
    bankAccountNumber: '50200028192831',
    bankIfsc: 'HDFC0000502',
    paymentTerms: 'Advance 50%, Balance on Dispatch',
    complianceStatus: 'VERIFIED',
    leadTimeDays: 5,
    status: 'ACTIVE',
    notes: 'FR-LSH copper wiring, Schneider Vivace switches, ABB distribution boards and smart relays.'
  },
  {
    id: 'VEND-004',
    vendorNo: 'VEND-2004',
    name: 'Kohler & Jaquar Luxury Bath Showroom',
    tradeSpecialty: 'PLUMBING_SANITARY',
    contactPerson: 'Pooja Anand',
    phone: '+91 99991 33412',
    email: 'orders@luxurybathhouse.in',
    gstin: '07AAACK7788L1ZQ',
    pan: 'AAACK7788L',
    address: 'Ring Road, Lajpat Nagar IV',
    city: 'New Delhi',
    rating: 4.9,
    bankAccountNumber: '0281050019283',
    bankIfsc: 'UTIB0000281',
    paymentTerms: '30 Days Net',
    complianceStatus: 'VERIFIED',
    leadTimeDays: 6,
    status: 'ACTIVE',
    notes: 'Wall-hung water closets, concealed diverters, PEX piping, and thermostatic shower columns.'
  },
  {
    id: 'VEND-005',
    vendorNo: 'VEND-2005',
    name: 'UltraTech & Asian Paints Master Agency',
    tradeSpecialty: 'CIVIL_MASONRY',
    contactPerson: 'Rajendra Prasad',
    phone: '+91 98114 99012',
    email: 'r.prasad@cementpaint.in',
    gstin: '07AAACU9900M1ZR',
    pan: 'AAACU9900M',
    address: 'GT Karnal Road, Industrial Area',
    city: 'Delhi',
    rating: 4.6,
    bankAccountNumber: '1092837465019',
    bankIfsc: 'SBIN0001092',
    paymentTerms: 'Weekly Settlement',
    complianceStatus: 'VERIFIED',
    leadTimeDays: 2,
    status: 'ACTIVE',
    notes: 'OPC 53 Grade Cement, ready-mix plaster, waterproofing chemicals, and Royale Luxury emulsion.'
  }
];

export const DEFAULT_RESOURCES: ResourceMaster[] = [
  {
    id: 'RES-001',
    resourceNo: 'RES-3001',
    name: 'Ram Avtar Sharma (Master Carpenter)',
    trade: 'CARPENTRY_JOINERY',
    skillLevel: 'MASTER_CRAFTSMAN',
    dailyWageRate: 1400,
    hourlyRate: 175,
    overtimeMultiplier: 1.5,
    standardDailyOutput: '15 sq.ft premium carcass joinery / day',
    employmentType: 'DIRECT_PAYROLL',
    phone: '+91 97110 33421',
    crewSize: 6,
    status: 'ALLOCATED',
    notes: 'Specialist in Blum hardware alignment, acrylic edge banding, and curved fluted paneling.'
  },
  {
    id: 'RES-002',
    resourceNo: 'RES-3002',
    name: 'Mohammad Idris (Senior Tile Mason)',
    trade: 'FLOORING_TILING',
    skillLevel: 'MASTER_CRAFTSMAN',
    dailyWageRate: 1200,
    hourlyRate: 150,
    overtimeMultiplier: 1.5,
    standardDailyOutput: '80 sq.ft vitrified / 50 sq.ft Italian marble laying / day',
    employmentType: 'PIECE_RATE_CONTRACT',
    phone: '+91 98119 77210',
    crewSize: 4,
    status: 'AVAILABLE',
    notes: 'Laser leveling expert with 2mm tile spacer clips and epoxy grout finishing.'
  },
  {
    id: 'RES-003',
    resourceNo: 'RES-3003',
    name: 'Suresh Chandra (Licensed Electrician)',
    trade: 'ELECTRICAL_AUTOMATION',
    skillLevel: 'SKILLED_TRADESMAN',
    dailyWageRate: 1100,
    hourlyRate: 137.5,
    overtimeMultiplier: 1.5,
    standardDailyOutput: '8 light/power points conduit & pulling / day',
    employmentType: 'DIRECT_PAYROLL',
    phone: '+91 96541 22891',
    crewSize: 3,
    status: 'AVAILABLE',
    notes: 'Holds Indian CPWD Wireman Grade-1 license; smart automation and DALI lighting specialist.'
  },
  {
    id: 'RES-004',
    resourceNo: 'RES-3004',
    name: 'Gopal Yadav (False Ceiling Lead Fabricator)',
    trade: 'FALSE_CEILINGS',
    skillLevel: 'SKILLED_TRADESMAN',
    dailyWageRate: 1050,
    hourlyRate: 131.25,
    overtimeMultiplier: 1.5,
    standardDailyOutput: '120 sq.ft GI framing & board fixing / day',
    employmentType: 'SUBCONTRACT_CREW',
    phone: '+91 98734 55123',
    crewSize: 5,
    status: 'AVAILABLE',
    notes: 'Gyproc certified installer for stepped coves, magnetic tracks, and perimeter shadow lines.'
  },
  {
    id: 'RES-005',
    resourceNo: 'RES-3005',
    name: 'Dinesh Kumar (Painter & Polish Master)',
    trade: 'PAINTING_POLISHING',
    skillLevel: 'SKILLED_TRADESMAN',
    dailyWageRate: 950,
    hourlyRate: 118.75,
    overtimeMultiplier: 1.5,
    standardDailyOutput: '150 sq.ft 3-coat putty sanding & primer / day',
    employmentType: 'PIECE_RATE_CONTRACT',
    phone: '+91 99112 88471',
    crewSize: 4,
    status: 'AVAILABLE',
    notes: 'Airless spray gun expert for PU luxury polish on teak veneers and zero-VOC emulsion.'
  },
  {
    id: 'RES-006',
    resourceNo: 'RES-3006',
    name: 'General Site Labor Gang (4 Helpers)',
    trade: 'CIVIL_MASONRY',
    skillLevel: 'GENERAL_HELPER',
    dailyWageRate: 650,
    hourlyRate: 81.25,
    overtimeMultiplier: 1.5,
    standardDailyOutput: 'Site debris shifting, unloading, curing, floor protection masking',
    employmentType: 'DIRECT_PAYROLL',
    phone: '+91 98110 00001',
    crewSize: 4,
    status: 'ALLOCATED',
    notes: 'Mandatory daily site cleanup, dust protection, and material intake logistics.'
  }
];

export const DEFAULT_WORK_PACKAGES: WorkPackageMaster[] = [
  {
    id: 'WP-01',
    code: 'WP-DEM',
    trade: 'DEMOLITION_DISPOSAL',
    name: 'Site Protection & Civil Demolition',
    standardWastagePercent: 0,
    defaultGstPercent: 18,
    hsnSacCode: '995419',
    mandatoryInclusions: ['Floor protection corflute sheets', 'Debris sorting and bagging', 'Municipal dumping truck permits'],
    standardExclusions: ['Structural beam/column breaking', 'Hazardous asbestos removal'],
    leadTimeWeeks: 1
  },
  {
    id: 'WP-02',
    code: 'WP-CIV',
    trade: 'CIVIL_MASONRY',
    name: 'Masonry, Screeding & Wet Works',
    standardWastagePercent: 5,
    defaultGstPercent: 18,
    hsnSacCode: '995411',
    mandatoryInclusions: ['Chicken mesh at brick-concrete joints', '7-day chemical curing', 'PPC cement mortar 1:4'],
    standardExclusions: ['RCC slab structural retrofitting'],
    leadTimeWeeks: 2
  },
  {
    id: 'WP-03',
    code: 'WP-WAT',
    trade: 'WATERPROOFING',
    name: 'Chemical Waterproofing & Ponding Test',
    standardWastagePercent: 5,
    defaultGstPercent: 18,
    hsnSacCode: '995429',
    mandatoryInclusions: ['Corner coving fillets', '2 coats acrylic elastomeric membrane', '72-hour ponding test signoff'],
    standardExclusions: ['External building facade cracks beyond balcony boundary'],
    leadTimeWeeks: 1
  },
  {
    id: 'WP-04',
    code: 'WP-FLR',
    trade: 'FLOORING_TILING',
    name: 'Vitrified Tiles & Italian Marble Laying',
    standardWastagePercent: 7,
    defaultGstPercent: 18,
    hsnSacCode: '995424',
    mandatoryInclusions: ['Epoxy grout for wet areas', 'Paper tape edge masking', 'POP protective slurry on fresh marble'],
    standardExclusions: ['Diamond polishing more than 7 stages unless quoted'],
    leadTimeWeeks: 3
  },
  {
    id: 'WP-05',
    code: 'WP-CEIL',
    trade: 'FALSE_CEILINGS',
    name: 'Gypsum Ceilings, Coves & Acoustic Panels',
    standardWastagePercent: 8,
    defaultGstPercent: 18,
    hsnSacCode: '995421',
    mandatoryInclusions: ['0.5mm GI framing channels', 'Fiber tape joints', 'Cove lighting channel routing'],
    standardExclusions: ['Decorative wooden rafters (measured under Joinery)'],
    leadTimeWeeks: 2
  },
  {
    id: 'WP-06',
    code: 'WP-JOIN',
    trade: 'CARPENTRY_JOINERY',
    name: 'Fixed Joinery, Paneling & Door Frames',
    standardWastagePercent: 10,
    defaultGstPercent: 18,
    hsnSacCode: '995426',
    mandatoryInclusions: ['BWP plywood calibration', 'Termite treatment coating', 'Soft-close hinges & telescopic channels'],
    standardExclusions: ['Loose mattresses and decorative soft furnishings'],
    leadTimeWeeks: 4
  },
  {
    id: 'WP-07',
    code: 'WP-ELEC',
    trade: 'ELECTRICAL_AUTOMATION',
    name: 'Electrical Conduiting, Wiring & DB Panels',
    standardWastagePercent: 8,
    defaultGstPercent: 18,
    hsnSacCode: '995461',
    mandatoryInclusions: ['FRLSH 1100V copper wires', 'Modular metal backboxes', 'Megger insulation testing certificate'],
    standardExclusions: ['Chandelier procurement (installation only included)'],
    leadTimeWeeks: 3
  },
  {
    id: 'WP-08',
    code: 'WP-PLUMB',
    trade: 'PLUMBING_SANITARY',
    name: 'Internal Plumbing, CPVC Lines & Sanitaryware',
    standardWastagePercent: 5,
    defaultGstPercent: 18,
    hsnSacCode: '995462',
    mandatoryInclusions: ['SDR-11 CPVC water lines', 'Hydrostatic pressure test at 10 bar', 'Brass extension nipples'],
    standardExclusions: ['Central solar water heater collector panels'],
    leadTimeWeeks: 2
  }
];

export const DEFAULT_UOMS: UOMMaster[] = [
  { code: 'sq.ft', name: 'Square Feet', description: 'Standard imperial area unit for floors, walls, ceilings & woodwork', precision: 2, dimensionType: 'AREA' },
  { code: 'sq.m', name: 'Square Meters', description: 'Metric area measurement for facade and large civil areas', precision: 2, dimensionType: 'AREA' },
  { code: 'r.ft', name: 'Running Feet', description: 'Linear measurement for skirtings, coves, conduits, and borders', precision: 1, dimensionType: 'LENGTH' },
  { code: 'nos', name: 'Numbers / Pieces', description: 'Discrete item units for doors, lights, sanitary fixtures, appliances', precision: 0, dimensionType: 'COUNT' },
  { code: 'lump sum', name: 'Lump Sum (LS)', description: 'Consolidated package scope or provisional budget allowance', precision: 0, dimensionType: 'LUMP_SUM' },
  { code: 'cum', name: 'Cubic Meters', description: 'Volumetric measurement for concrete and earthwork', precision: 3, dimensionType: 'VOLUME' },
  { code: 'cft', name: 'Cubic Feet', description: 'Timber log and sand volume measurement', precision: 2, dimensionType: 'VOLUME' },
  { code: 'kg', name: 'Kilograms', description: 'Weight measurement for steel rebars and hardware fixings', precision: 2, dimensionType: 'WEIGHT' },
  { code: 'metric ton', name: 'Metric Ton (MT)', description: 'Bulk structural steel and cement delivery', precision: 2, dimensionType: 'WEIGHT' },
  { code: 'point', name: 'Electrical Point', description: 'Electrical switch to light/fan/socket looping circuit', precision: 0, dimensionType: 'COUNT' }
];

export const DEFAULT_TAX_RULES: TaxRuleMaster[] = [
  { id: 'TAX-01', code: 'GST-WC-18', name: 'Composite Works Contract GST', gstRatePercent: 18, applicableHSNSAC: '995411 / 995426', description: 'Standard unified Indian GST rate applicable on Turnkey Interior & Architectural Construction contracts containing both goods and labour.' },
  { id: 'TAX-02', code: 'GST-MAT-28', name: 'Luxury Stone & Glazing Goods', gstRatePercent: 28, applicableHSNSAC: '6802 / 7007', description: 'Applicable on standalone procurement of imported marble, granite slabs, and acoustic architectural glass.' },
  { id: 'TAX-03', code: 'GST-WOOD-12', name: 'Timber & Flush Doors Goods', gstRatePercent: 12, applicableHSNSAC: '4410 / 4412', description: 'Applicable on raw timber logs, particle boards, and specified flush doors.' },
  { id: 'TAX-04', code: 'GST-AGG-05', name: 'Aggregates, Sand & Bricks', gstRatePercent: 5, applicableHSNSAC: '2505 / 6901', description: 'Concessional GST on river sand, stone dust, and fly-ash bricks for civil masonry.' }
];
