/**
 * Build Storys ERP - Master Rate Library
 * Standard Construction & Interior Turnkey Rate Master with HSN/SAC codes,
 * deterministic unit rates broken down by Material, Labour, Equipment, and Subcontract.
 */

import { MasterRateItem } from '../types/erp';

export const DEFAULT_MASTER_RATES: MasterRateItem[] = [
  // 1. DEMOLITION & DISPOSAL
  {
    id: 'RATE-DEM-001',
    itemCode: 'DEM-01',
    trade: 'DEMOLITION_DISPOSAL',
    workPackage: 'Civil Demolition',
    description: 'Dismantling existing brick masonry/AAC block partition wall without damaging structural slab or beams, including debris sorting.',
    specification: 'Manual chiseling and electrical breaker, 4.5" to 9" wall thickness',
    brandGrade: 'On-site standard safety equipment',
    unit: 'sq.ft',
    materialRate: 0,
    labourRate: 22,
    equipmentRate: 6,
    subcontractRate: 0,
    totalUnitCost: 28,
    defaultMarkupPercent: 25,
    suggestedSellingRate: 35,
    rateSource: 'APPROVED_MASTER',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-01-15',
    status: 'APPROVED',
    hsnSacCode: '995419',
    gstRate: 18
  },
  {
    id: 'RATE-DEM-002',
    itemCode: 'DEM-02',
    trade: 'DEMOLITION_DISPOSAL',
    workPackage: 'Civil Demolition',
    description: 'Hacking existing ceramic/vitrified floor tiles & mortar bed up to 50mm, carting away debris to municipal dumping ground via approved tractor/truck trips.',
    specification: 'Floor tile removal with 40mm screed breaking and bagging',
    brandGrade: 'Standard carting',
    unit: 'sq.ft',
    materialRate: 0,
    labourRate: 26,
    equipmentRate: 8,
    subcontractRate: 10,
    totalUnitCost: 44,
    defaultMarkupPercent: 25,
    suggestedSellingRate: 55,
    rateSource: 'APPROVED_MASTER',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-01-15',
    status: 'APPROVED',
    hsnSacCode: '995419',
    gstRate: 18
  },

  // 2. CIVIL & MASONRY
  {
    id: 'RATE-CIV-001',
    itemCode: 'CIV-01',
    trade: 'CIVIL_MASONRY',
    workPackage: 'Internal Masonry',
    description: 'Constructing 4" thick autoclaved aerated concrete (AAC) block masonry using polymer thin-bed block jointing adhesive, including curing and wire-mesh RCC band at lintel level.',
    specification: 'Siporex/Birla Aerocon Grade 1 AAC blocks, 100mm thick',
    brandGrade: 'Birla Aerocon / Magicrete',
    unit: 'sq.ft',
    materialRate: 75,
    labourRate: 35,
    equipmentRate: 5,
    subcontractRate: 0,
    totalUnitCost: 115,
    defaultMarkupPercent: 20,
    suggestedSellingRate: 138,
    rateSource: 'APPROVED_MASTER',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-01-10',
    status: 'APPROVED',
    hsnSacCode: '995411',
    gstRate: 18
  },
  {
    id: 'RATE-CIV-002',
    itemCode: 'CIV-02',
    trade: 'CIVIL_MASONRY',
    workPackage: 'Plastering',
    description: 'Providing & applying 12mm-15mm smooth cement sand plaster in 1:4 mortar on internal masonry walls in line, level, and plumb including scaffolding.',
    specification: 'UltraTech/ACC OPC 53 grade cement and washed river sand',
    brandGrade: 'UltraTech Super',
    unit: 'sq.ft',
    materialRate: 28,
    labourRate: 24,
    equipmentRate: 3,
    subcontractRate: 0,
    totalUnitCost: 55,
    defaultMarkupPercent: 22,
    suggestedSellingRate: 67,
    rateSource: 'APPROVED_MASTER',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-01-10',
    status: 'APPROVED',
    hsnSacCode: '995411',
    gstRate: 18
  },

  // 3. WATERPROOFING
  {
    id: 'RATE-WTR-001',
    itemCode: 'WTR-01',
    trade: 'WATERPROOFING',
    workPackage: 'Wet Areas & Balconies',
    description: 'Two-component acrylic modified cementitious elastomeric waterproofing membrane coating with 2 coats crosswise, including 150mm cove fillet at floor-wall junction and pond testing for 72 hrs.',
    specification: 'Dr. Fixit Fastflex or SikaTop Seal 107',
    brandGrade: 'Pidilite / Sika',
    unit: 'sq.ft',
    materialRate: 48,
    labourRate: 28,
    equipmentRate: 4,
    subcontractRate: 0,
    totalUnitCost: 80,
    defaultMarkupPercent: 25,
    suggestedSellingRate: 100,
    rateSource: 'APPROVED_MASTER',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-02-01',
    status: 'APPROVED',
    hsnSacCode: '995413',
    gstRate: 18
  },

  // 4. FLOORING & TILING
  {
    id: 'RATE-FLR-001',
    itemCode: 'FLR-01',
    trade: 'FLOORING_TILING',
    workPackage: 'Main Flooring',
    description: 'Laying 1200x600mm / 1600x800mm Glazed Vitrified Tiles (GVT) with rectified edges over polymer-modified tile adhesive bed, including 2mm spacer joints with epoxy grout.',
    specification: 'Double charged / GVT matte or satin finish, min 9mm thickness',
    brandGrade: 'Kajaria / Somany / Qutone',
    unit: 'sq.ft',
    materialRate: 110,
    labourRate: 42,
    equipmentRate: 6,
    subcontractRate: 0,
    totalUnitCost: 158,
    defaultMarkupPercent: 22,
    suggestedSellingRate: 195,
    rateSource: 'APPROVED_MASTER',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-01-20',
    status: 'APPROVED',
    hsnSacCode: '995419',
    gstRate: 18
  },
  {
    id: 'RATE-FLR-002',
    itemCode: 'FLR-02',
    trade: 'FLOORING_TILING',
    workPackage: 'Luxury Stone Flooring',
    description: 'Supplying and installing imported Italian Marble (Bottochino / Statuario / Grey William) 18mm thickness, wet bed mortar laying, diamond mirror polishing with 8 grades of resin pads and sealer.',
    specification: 'Imported slab gangsaw cut, bookmatched, crystal mirror polish',
    brandGrade: 'Imported First Quality',
    unit: 'sq.ft',
    materialRate: 480,
    labourRate: 120,
    equipmentRate: 35,
    subcontractRate: 0,
    totalUnitCost: 635,
    defaultMarkupPercent: 20,
    suggestedSellingRate: 760,
    rateSource: 'APPROVED_MASTER',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-01-20',
    status: 'APPROVED',
    hsnSacCode: '995419',
    gstRate: 18
  },
  {
    id: 'RATE-FLR-003',
    itemCode: 'FLR-03',
    trade: 'FLOORING_TILING',
    workPackage: 'Wooden Flooring',
    description: 'Supplying and installing AC4 grade 8mm/10mm Engineered Wooden / Laminate Flooring with 2mm high-density sound dampening underlay and perimeter matching skirting.',
    specification: 'Click-lock tongue-and-groove system with moisture-resistant core',
    brandGrade: 'Pergo / Quick-Step / Greenpanel',
    unit: 'sq.ft',
    materialRate: 155,
    labourRate: 30,
    equipmentRate: 5,
    subcontractRate: 0,
    totalUnitCost: 190,
    defaultMarkupPercent: 25,
    suggestedSellingRate: 238,
    rateSource: 'APPROVED_MASTER',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-02-05',
    status: 'APPROVED',
    hsnSacCode: '995419',
    gstRate: 18
  },

  // 5. FALSE CEILINGS
  {
    id: 'RATE-CLG-001',
    itemCode: 'CLG-01',
    trade: 'FALSE_CEILINGS',
    workPackage: 'Gypsum Ceilings',
    description: 'Providing and fixing 12.5mm tapered edge Gypsum Board false ceiling on perimeter channel, intermediate channel, and ceiling section frame, with drywall screws, paper tape and jointing compound.',
    specification: 'Gypsteel ULTRA GI framing with Gypboard Plain 12.5mm',
    brandGrade: 'Saint-Gobain Gyproc',
    unit: 'sq.ft',
    materialRate: 62,
    labourRate: 38,
    equipmentRate: 5,
    subcontractRate: 0,
    totalUnitCost: 105,
    defaultMarkupPercent: 25,
    suggestedSellingRate: 132,
    rateSource: 'APPROVED_MASTER',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-01-25',
    status: 'APPROVED',
    hsnSacCode: '995419',
    gstRate: 18
  },
  {
    id: 'RATE-CLG-002',
    itemCode: 'CLG-02',
    trade: 'FALSE_CEILINGS',
    workPackage: 'Perimeter Cove',
    description: 'Providing peripheral architectural indirect LED light cove step in gypsum ceiling with 150mm vertical baffle and light recess.',
    specification: 'Framed vertical drop with reinforced edge bead',
    brandGrade: 'Saint-Gobain Gyproc',
    unit: 'r.ft',
    materialRate: 70,
    labourRate: 45,
    equipmentRate: 5,
    subcontractRate: 0,
    totalUnitCost: 120,
    defaultMarkupPercent: 25,
    suggestedSellingRate: 150,
    rateSource: 'APPROVED_MASTER',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-01-25',
    status: 'APPROVED',
    hsnSacCode: '995419',
    gstRate: 18
  },

  // 6. PAINTING & POLISHING
  {
    id: 'RATE-PNT-001',
    itemCode: 'PNT-01',
    trade: 'PAINTING_POLISHING',
    workPackage: 'Internal Wall Painting',
    description: 'Surface preparation, applying 1 coat acrylic primer, 2 coats polymer white wall putty sanding with orbital sander, and 2-3 coats luxury sheen emulsion.',
    specification: 'Teflon surface protector luxury emulsion, anti-bacterial',
    brandGrade: 'Asian Paints Royale Luxury / Berger Silk Glamor',
    unit: 'sq.ft',
    materialRate: 22,
    labourRate: 23,
    equipmentRate: 3,
    subcontractRate: 0,
    totalUnitCost: 48,
    defaultMarkupPercent: 25,
    suggestedSellingRate: 60,
    rateSource: 'APPROVED_MASTER',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-02-10',
    status: 'APPROVED',
    hsnSacCode: '995419',
    gstRate: 18
  },
  {
    id: 'RATE-PNT-002',
    itemCode: 'PNT-02',
    trade: 'PAINTING_POLISHING',
    workPackage: 'Wood Polish & PU',
    description: 'Providing & applying Italian Polyurethane (PU) clear/pigmented satin coat on wood veneers/MDF surfaces including sealer, primer, wet sanding, and dust-free spray application.',
    specification: '2-pack acrylic PU with non-yellowing aliphatic hardener',
    brandGrade: 'Sirca / ICA Italian PU',
    unit: 'sq.ft',
    materialRate: 120,
    labourRate: 90,
    equipmentRate: 20,
    subcontractRate: 0,
    totalUnitCost: 230,
    defaultMarkupPercent: 25,
    suggestedSellingRate: 288,
    rateSource: 'APPROVED_MASTER',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-02-10',
    status: 'APPROVED',
    hsnSacCode: '995419',
    gstRate: 18
  },

  // 7. ELECTRICAL & AUTOMATION
  {
    id: 'RATE-ELE-001',
    itemCode: 'ELE-01',
    trade: 'ELECTRICAL_AUTOMATION',
    workPackage: 'Point Wiring',
    description: 'Internal concealed point wiring for light, fan, 6A socket points with FRLS copper multi-strand wire in rigid PVC conduit recessed in walls/ceilings, with modular grid plates.',
    specification: '1.5 sq.mm FR PVC insulated copper wires in Medium Duty PVC conduits',
    brandGrade: 'Havells / Polycab wires + Legrand Arteor / Schneider sockets',
    unit: 'point',
    materialRate: 680,
    labourRate: 380,
    equipmentRate: 40,
    subcontractRate: 0,
    totalUnitCost: 1100,
    defaultMarkupPercent: 25,
    suggestedSellingRate: 1375,
    rateSource: 'APPROVED_MASTER',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-01-15',
    status: 'APPROVED',
    hsnSacCode: '995414',
    gstRate: 18
  },
  {
    id: 'RATE-ELE-002',
    itemCode: 'ELE-02',
    trade: 'ELECTRICAL_AUTOMATION',
    workPackage: 'Power Wiring',
    description: 'Providing and installing 16A/25A dedicated power point for AC/Geyser/Oven with 4 sq.mm copper wire and separate 2.5 sq.mm earth in conduit with MCB in sub-distribution box.',
    specification: 'Dedicated heavy load home-run circuit with 16A/20A SP MCB',
    brandGrade: 'Havells / Polycab + Schneider Acti9',
    unit: 'point',
    materialRate: 1350,
    labourRate: 550,
    equipmentRate: 50,
    subcontractRate: 0,
    totalUnitCost: 1950,
    defaultMarkupPercent: 25,
    suggestedSellingRate: 2438,
    rateSource: 'APPROVED_MASTER',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-01-15',
    status: 'APPROVED',
    hsnSacCode: '995414',
    gstRate: 18
  },

  // 8. PLUMBING & SANITARY
  {
    id: 'RATE-PLB-001',
    itemCode: 'PLB-01',
    trade: 'PLUMBING_SANITARY',
    workPackage: 'Concealed Water Supply',
    description: 'Supplying and fixing CPVC SDR-11 piping network for hot and cold water distribution concealed inside chase with pressure testing at 10 bar for 24 hours.',
    specification: '1/2" to 1" CPVC Class 1 pipe with solvent welding',
    brandGrade: 'Astral / Ashirvad',
    unit: 'r.ft',
    materialRate: 125,
    labourRate: 75,
    equipmentRate: 15,
    subcontractRate: 0,
    totalUnitCost: 215,
    defaultMarkupPercent: 25,
    suggestedSellingRate: 269,
    rateSource: 'APPROVED_MASTER',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-01-18',
    status: 'APPROVED',
    hsnSacCode: '995415',
    gstRate: 18
  },

  // 9. MODULAR KITCHEN & JOINERY
  {
    id: 'RATE-KIT-001',
    itemCode: 'KIT-01',
    trade: 'MODULAR_KITCHEN',
    workPackage: 'Kitchen Carcass & Drawers',
    description: 'Custom modular kitchen base and overhead carcass using 18mm BWP (Boiling Water Proof) Marine Grade 710 calibrated plywood with 0.8mm internal off-white balancing laminate and 2mm PVC edge banding.',
    specification: 'IS 710 BWP Marine Plywood carcass, German soft-close tandem drawers',
    brandGrade: 'Greenply / CenturyPly Marine + Hafele / Hettich Hardware',
    unit: 'sq.ft',
    materialRate: 1250,
    labourRate: 350,
    equipmentRate: 50,
    subcontractRate: 0,
    totalUnitCost: 1650,
    defaultMarkupPercent: 25,
    suggestedSellingRate: 2060,
    rateSource: 'APPROVED_MASTER',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-02-01',
    status: 'APPROVED',
    hsnSacCode: '995419',
    gstRate: 18
  },
  {
    id: 'RATE-KIT-002',
    itemCode: 'KIT-02',
    trade: 'MODULAR_KITCHEN',
    workPackage: 'Kitchen Shutters',
    description: 'High-gloss seamless 1.5mm Acrylic or PU lacquered shutters on 18mm HDHMR (High Density High Moisture Resistance) board with matching zero-joint laser edge-banded profiles.',
    specification: 'HDHMR Action TESA with imported Senoplast/Rehau Acrylic surface',
    brandGrade: 'Action TESA HDHMR + Rehau Edge Banding',
    unit: 'sq.ft',
    materialRate: 650,
    labourRate: 180,
    equipmentRate: 30,
    subcontractRate: 0,
    totalUnitCost: 860,
    defaultMarkupPercent: 25,
    suggestedSellingRate: 1075,
    rateSource: 'APPROVED_MASTER',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-02-01',
    status: 'APPROVED',
    hsnSacCode: '995419',
    gstRate: 18
  },
  {
    id: 'RATE-KIT-003',
    itemCode: 'KIT-03',
    trade: 'MODULAR_KITCHEN',
    workPackage: 'Countertop',
    description: 'Supplying and installing 18mm Quartz or Granite kitchen countertop with 40mm sandwich fascia moulding, sink cutout with polished inner edges, and 100mm back splash.',
    specification: 'Engineered Quartz slab with scratch and stain resistance',
    brandGrade: 'KalingaStone / Caesarstone / Black Pearl Granite',
    unit: 'sq.ft',
    materialRate: 380,
    labourRate: 140,
    equipmentRate: 30,
    subcontractRate: 0,
    totalUnitCost: 550,
    defaultMarkupPercent: 22,
    suggestedSellingRate: 670,
    rateSource: 'APPROVED_MASTER',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-02-01',
    status: 'APPROVED',
    hsnSacCode: '995419',
    gstRate: 18
  },

  // 10. WARDROBES & STORAGE
  {
    id: 'RATE-WRD-001',
    itemCode: 'WRD-01',
    trade: 'WARDROBES_STORAGE',
    workPackage: 'Built-in Sliding Wardrobe',
    description: 'Floor-to-ceiling built-in sliding wardrobe carcass in 18mm BWR commercial grade calibrated plywood with 1mm laminate internal lining, hanging rails, internal drawers, and top-hung heavy duty soft-close sliding track system.',
    specification: 'IS 303 BWR plywood with Hafele In-Line sliding hardware',
    brandGrade: 'Century Pro BWR + Hafele Slido',
    unit: 'sq.ft',
    materialRate: 1100,
    labourRate: 320,
    equipmentRate: 40,
    subcontractRate: 0,
    totalUnitCost: 1460,
    defaultMarkupPercent: 25,
    suggestedSellingRate: 1825,
    rateSource: 'APPROVED_MASTER',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-01-28',
    status: 'APPROVED',
    hsnSacCode: '995419',
    gstRate: 18
  },
  {
    id: 'RATE-WRD-002',
    itemCode: 'WRD-02',
    trade: 'WARDROBES_STORAGE',
    workPackage: 'Wardrobe Shutters',
    description: 'Wardrobe shutters finished with natural smoked teak/walnut veneer pressed on 18mm HDHMR, grooved CNC patterns, PU matte polish finish with integrated concealed edge handles.',
    specification: 'Natural architectural veneer with water-based PU matte finish',
    brandGrade: 'Turakhia / Decowood Veneers',
    unit: 'sq.ft',
    materialRate: 580,
    labourRate: 220,
    equipmentRate: 30,
    subcontractRate: 0,
    totalUnitCost: 830,
    defaultMarkupPercent: 25,
    suggestedSellingRate: 1038,
    rateSource: 'APPROVED_MASTER',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-01-28',
    status: 'APPROVED',
    hsnSacCode: '995419',
    gstRate: 18
  },

  // 11. DOORS, WINDOWS & HARDWARE
  {
    id: 'RATE-DOR-001',
    itemCode: 'DOR-01',
    trade: 'DOORS_WINDOWS_GLAZING',
    workPackage: 'Internal Flush Doors',
    description: 'Supplying and installing 38mm thick solid core flush doors (IS 2202) both sides pressed with 1mm laminate or natural veneer, hardwood door frame (Chowkhat) with acoustic rubber gasket and heavy duty SS 304 ball-bearing hinges.',
    specification: 'Solid pine/meranti timber infill core, water resistant',
    brandGrade: 'Greenply Flush Doors + Dorset Architectural Hardware',
    unit: 'nos',
    materialRate: 7500,
    labourRate: 2200,
    equipmentRate: 300,
    subcontractRate: 0,
    totalUnitCost: 10000,
    defaultMarkupPercent: 25,
    suggestedSellingRate: 12500,
    rateSource: 'APPROVED_MASTER',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-01-15',
    status: 'APPROVED',
    hsnSacCode: '995419',
    gstRate: 18
  },

  // 12. PROVISIONAL ITEM (MISSING / PROVISIONAL RATE EXAMPLE)
  {
    id: 'RATE-PROV-001',
    itemCode: 'SPL-01',
    trade: 'CARPENTRY_JOINERY',
    workPackage: 'Custom Feature Paneling',
    description: 'Custom acoustic fluted charcoal wall paneling behind master bed with concealed warm 3000K LED profile channel.',
    specification: 'Provisional specification pending client brand sign-off',
    brandGrade: 'Provisional - To be approved',
    unit: 'sq.ft',
    materialRate: 280,
    labourRate: 90,
    equipmentRate: 15,
    subcontractRate: 0,
    totalUnitCost: 385,
    defaultMarkupPercent: 20,
    suggestedSellingRate: 462,
    rateSource: 'ILLUSTRATIVE_BENCHMARK',
    location: 'NCR / Metro Urban',
    effectiveDate: '2026-02-15',
    status: 'PROVISIONAL',
    hsnSacCode: '995419',
    gstRate: 18
  }
];
