/**
 * Build Storys ERP - Preloaded Synthetic Demo Data
 * Demonstrates a high-end 3BHK Residential Interior & Turnkey Renovation project
 * adhering to all 8 required demonstration criteria.
 */

import { ProjectRecord, BOQItem, BOQRevision, CustomerQuotation, AlternativePackageOption, ValueEngineeringOption } from '../types/erp';

export function getSyntheticDemoProject(): ProjectRecord {
  const projectId = 'PROJ-SKYLINE-1402';
  const rev0Id = 'REV-0-AI-DRAFT';
  const rev1Id = 'REV-1-ESTIMATOR-APPROVED';

  const demoBOQItemsRev0: BOQItem[] = [
    // Civil & Demolition
    {
      id: 'BOQ-001',
      boqRevisionId: rev0Id,
      itemCode: 'DEM-01',
      trade: 'DEMOLITION_DISPOSAL',
      workPackage: 'Civil Demolition',
      floor: '14th Floor',
      roomZone: 'Living & Dining Area',
      description: 'Dismantling existing non-load-bearing partition wall between dining and study including dust containment and debris removal.',
      specification: 'Manual electrical breaker, 4.5" brick partition',
      brandGrade: 'Standard Safety Gear',
      inclusions: 'Hacking, bagging, manual loading to freight elevator, tractor transport to municipal yard',
      exclusions: 'Structural beam/column chipping',
      unit: 'sq.ft',
      length: 12,
      width: 0.375,
      height: 9.5,
      quantityFormula: '12 ft length * 9.5 ft height = 114 sq.ft',
      baseQuantity: 114,
      wastagePercent: 5,
      finalQuantity: 119.7,
      quantityType: 'MEASURED',
      materialRate: 0,
      labourRate: 22,
      equipmentRate: 6,
      subcontractRate: 0,
      unitCost: 28,
      totalCost: 3351.6,
      markupPercent: 25,
      sellingRate: 35,
      sellingAmount: 4189.5,
      rateSource: 'APPROVED_MASTER',
      rateStatus: 'APPROVED',
      sourceDocumentRef: 'Skyline_1402_Architectural_FloorPlan_RevB.pdf (Page 2)',
      assumptions: 'Freight lift accessible during approved working hours 10am-6pm.',
      isApprovedByEstimator: false
    },
    {
      id: 'BOQ-002',
      boqRevisionId: rev0Id,
      itemCode: 'WTR-01',
      trade: 'WATERPROOFING',
      workPackage: 'Wet Areas',
      floor: '14th Floor',
      roomZone: 'Master Ensuite Bathroom',
      description: '2-component acrylic elastomeric waterproofing membrane over bathroom sunken floor and wall dado up to 7ft.',
      specification: 'Dr. Fixit Fastflex 2 coats with fiber mesh at corner fillets',
      brandGrade: 'Pidilite Dr. Fixit Fastflex',
      inclusions: 'Pond testing for 72 hours with water level certification',
      exclusions: 'Plumbing core cutting',
      unit: 'sq.ft',
      length: 8,
      width: 6.5,
      height: 7,
      quantityFormula: '(8 * 6.5 floor) + 2*(8+6.5)*7 wall dado = 52 + 203 = 255 sq.ft',
      baseQuantity: 255,
      wastagePercent: 6,
      finalQuantity: 270.3,
      quantityType: 'MEASURED',
      materialRate: 48,
      labourRate: 28,
      equipmentRate: 4,
      subcontractRate: 0,
      unitCost: 80,
      totalCost: 21624,
      markupPercent: 25,
      sellingRate: 100,
      sellingAmount: 27030,
      rateSource: 'APPROVED_MASTER',
      rateStatus: 'APPROVED',
      sourceDocumentRef: 'Site_Survey_Civil_Structural_Inspection.pdf (Section 4)',
      assumptions: 'Full 72hr pond testing required before floor tiling starts.',
      isApprovedByEstimator: false
    },

    // Flooring & Tiling
    {
      id: 'BOQ-003',
      boqRevisionId: rev0Id,
      itemCode: 'FLR-01',
      trade: 'FLOORING_TILING',
      workPackage: 'Main Flooring',
      floor: '14th Floor',
      roomZone: 'Living & Dining Lounge',
      description: 'Laying 1600x800mm High Gloss Glazed Vitrified Tiles (GVT) Italian marble design over polymer-modified adhesive bed with epoxy joints.',
      specification: 'Rectified edge, 9.5mm vitrified tile with 2mm leveling spacer clips',
      brandGrade: 'Kajaria Eternity / Somany Max',
      inclusions: 'Epoxy grout, edge polishing, 100mm matching skirting',
      exclusions: 'Floor underlay acoustic mat',
      unit: 'sq.ft',
      length: 24,
      width: 14.5,
      quantityFormula: '24 ft * 14.5 ft = 348 sq.ft + 77 r.ft skirting (38.5 sq.ft) = 386.5 sq.ft',
      baseQuantity: 386.5,
      wastagePercent: 8,
      finalQuantity: 417.42,
      quantityType: 'MEASURED',
      materialRate: 110,
      labourRate: 42,
      equipmentRate: 6,
      subcontractRate: 0,
      unitCost: 158,
      totalCost: 65952.36,
      markupPercent: 23.4,
      sellingRate: 195,
      sellingAmount: 81396.9,
      rateSource: 'APPROVED_MASTER',
      rateStatus: 'APPROVED',
      sourceDocumentRef: 'Skyline_1402_Architectural_FloorPlan_RevB.pdf (Page 1)',
      assumptions: 'Pattern match layout to be signed off by Architect before dry lay.',
      isApprovedByEstimator: false
    },
    {
      id: 'BOQ-004',
      boqRevisionId: rev0Id,
      itemCode: 'FLR-03',
      trade: 'FLOORING_TILING',
      workPackage: 'Bedroom Flooring',
      floor: '14th Floor',
      roomZone: 'Master Bedroom Suite',
      description: 'Supplying and installing AC4 grade 10mm German engineered wooden flooring with sound dampening underlay and perimeter transition beading.',
      specification: 'Moisture resistant HDF core, click-lock installation',
      brandGrade: 'Pergo Living Expression',
      inclusions: '2mm acoustic foam underlay, moisture barrier sheet, skirting profile',
      exclusions: 'Sub-floor self leveling screed if floor variation exceeds 3mm',
      unit: 'sq.ft',
      length: 16,
      width: 13,
      quantityFormula: '16 ft * 13 ft = 208 sq.ft',
      baseQuantity: 208,
      wastagePercent: 7,
      finalQuantity: 222.56,
      quantityType: 'MEASURED',
      materialRate: 155,
      labourRate: 30,
      equipmentRate: 5,
      subcontractRate: 0,
      unitCost: 190,
      totalCost: 42286.4,
      markupPercent: 25.2,
      sellingRate: 238,
      sellingAmount: 52969.28,
      rateSource: 'APPROVED_MASTER',
      rateStatus: 'APPROVED',
      sourceDocumentRef: 'Client Moodboard (Ref: Warm Scandinavian Oak)',
      assumptions: 'Requires completely cured dry sub-floor prior to installation.',
      isApprovedByEstimator: false
    },

    // False Ceilings
    {
      id: 'BOQ-005',
      boqRevisionId: rev0Id,
      itemCode: 'CLG-01',
      trade: 'FALSE_CEILINGS',
      workPackage: 'Gypsum Ceiling',
      floor: '14th Floor',
      roomZone: 'Living & Dining Lounge',
      description: 'Providing and fixing Saint-Gobain Gyproc 12.5mm plain false ceiling suspended on Gypsteel ULTRA GI framing.',
      specification: '12.5mm tapered edge board with paper tape jointing compound',
      brandGrade: 'Saint-Gobain Gyproc Ultra',
      inclusions: 'GI suspension angles, rawl plugs, jointing compound, cutouts for downlights',
      exclusions: 'Light fixtures & magnetic track rails',
      unit: 'sq.ft',
      length: 24,
      width: 14.5,
      quantityFormula: '24 ft * 14.5 ft = 348 sq.ft',
      baseQuantity: 348,
      wastagePercent: 5,
      finalQuantity: 365.4,
      quantityType: 'MEASURED',
      materialRate: 62,
      labourRate: 38,
      equipmentRate: 5,
      subcontractRate: 0,
      unitCost: 105,
      totalCost: 38367,
      markupPercent: 25.7,
      sellingRate: 132,
      sellingAmount: 48232.8,
      rateSource: 'APPROVED_MASTER',
      rateStatus: 'APPROVED',
      sourceDocumentRef: 'Skyline_1402_Architectural_FloorPlan_RevB.pdf (Ceiling RCP)',
      assumptions: 'Slab height verified at 9.5 ft; false ceiling drop 6 inches.',
      isApprovedByEstimator: false
    },
    {
      id: 'BOQ-006',
      boqRevisionId: rev0Id,
      itemCode: 'CLG-02',
      trade: 'FALSE_CEILINGS',
      workPackage: 'Cove Step',
      floor: '14th Floor',
      roomZone: 'Living & Dining Lounge',
      description: 'Peripheral architectural indirect LED light cove step in gypsum ceiling with 150mm vertical baffle and recessed light reflector.',
      specification: 'Reinforced GI frame drop with edge trim bead',
      brandGrade: 'Saint-Gobain Gyproc Ultra',
      inclusions: 'Framing, baffle, jointing compound ready for painting',
      exclusions: 'LED strip light & driver supply',
      unit: 'r.ft',
      quantityFormula: 'Perimeter: 2 * (24 + 14.5) = 77 running ft',
      baseQuantity: 77,
      wastagePercent: 5,
      finalQuantity: 80.85,
      quantityType: 'MEASURED',
      materialRate: 70,
      labourRate: 45,
      equipmentRate: 5,
      subcontractRate: 0,
      unitCost: 120,
      totalCost: 9702,
      markupPercent: 25,
      sellingRate: 150,
      sellingAmount: 12127.5,
      rateSource: 'APPROVED_MASTER',
      rateStatus: 'APPROVED',
      sourceDocumentRef: 'Skyline_1402_Architectural_FloorPlan_RevB.pdf (Ceiling RCP)',
      assumptions: 'Perimeter alignment along perimeter walls.',
      isApprovedByEstimator: false
    },

    // Painting & Wall Finishes
    {
      id: 'BOQ-007',
      boqRevisionId: rev0Id,
      itemCode: 'PNT-01',
      trade: 'PAINTING_POLISHING',
      workPackage: 'Interior Wall Painting',
      floor: '14th Floor',
      roomZone: 'Entire 3BHK Apartment',
      description: 'Complete interior wall painting: surface prep, 1 coat acrylic primer, 2 coats white wall putty with orbital machine sanding, 2 coats luxury sheen emulsion.',
      specification: 'Asian Paints Royale Luxury Emulsion, stain-resistant formulation',
      brandGrade: 'Asian Paints Royale Luxury',
      inclusions: 'Masking of doors/windows, floor protection plastic sheet, final cleanup',
      exclusions: 'Specialized texture coats or metallic stencil work',
      unit: 'sq.ft',
      quantityFormula: 'Carpet area 1650 * 3.2 wall factor - openings = 4480 sq.ft',
      baseQuantity: 4480,
      wastagePercent: 5,
      finalQuantity: 4704,
      quantityType: 'MEASURED',
      materialRate: 22,
      labourRate: 23,
      equipmentRate: 3,
      subcontractRate: 0,
      unitCost: 48,
      totalCost: 225792,
      markupPercent: 25,
      sellingRate: 60,
      sellingAmount: 282240,
      rateSource: 'APPROVED_MASTER',
      rateStatus: 'APPROVED',
      sourceDocumentRef: 'Client Brief & Site Survey Report',
      assumptions: 'Shades: Morning Sun Royale Base & Cotton Wool for common spaces.',
      isApprovedByEstimator: false
    },

    // Electrical & Automation
    {
      id: 'BOQ-008',
      boqRevisionId: rev0Id,
      itemCode: 'ELE-01',
      trade: 'ELECTRICAL_AUTOMATION',
      workPackage: 'Concealed Wiring & Switches',
      floor: '14th Floor',
      roomZone: 'Entire 3BHK Apartment',
      description: 'Concealed electrical point wiring for light, fan, 6A sockets with FRLS multi-strand copper wire in heavy PVC conduit and premium modular grid plates.',
      specification: '1.5 sq.mm FR copper wires + Legrand Arteor modular switches',
      brandGrade: 'Polycab FRLS + Legrand Arteor White',
      inclusions: 'Conduit chase cutting, GI boxes, brass earth terminals, faceplates',
      exclusions: 'Light fixtures & fans',
      unit: 'point',
      quantityFormula: 'Counted from electrical single line drawing = 145 points',
      baseQuantity: 145,
      wastagePercent: 0,
      finalQuantity: 145,
      quantityType: 'MEASURED',
      materialRate: 680,
      labourRate: 380,
      equipmentRate: 40,
      subcontractRate: 0,
      unitCost: 1100,
      totalCost: 159500,
      markupPercent: 25,
      sellingRate: 1375,
      sellingAmount: 199375,
      rateSource: 'APPROVED_MASTER',
      rateStatus: 'APPROVED',
      sourceDocumentRef: 'Skyline_1402_Architectural_FloorPlan_RevB.pdf (Page 4 - Electrical SLD)',
      assumptions: 'Points mapped strictly to SLD revision B.',
      isApprovedByEstimator: false
    },
    {
      id: 'BOQ-009',
      boqRevisionId: rev0Id,
      itemCode: 'ELE-02',
      trade: 'ELECTRICAL_AUTOMATION',
      workPackage: 'Heavy Power Points',
      floor: '14th Floor',
      roomZone: 'Entire 3BHK Apartment',
      description: 'Dedicated heavy load 16A/25A power points for Air Conditioners (5 nos), Geysers (3 nos), Oven, Microwave, Hob, and Dishwasher.',
      specification: '4.0 sq.mm copper wire home-run with individual 16A/25A MCBs in sub-DB',
      brandGrade: 'Polycab FRLS + Schneider Acti9 MCB',
      inclusions: 'Heavy gauge conduit, individual earth conductor, modular AC starter switch',
      exclusions: 'AC copper refrigerant piping',
      unit: 'point',
      quantityFormula: 'AC (5) + Geyser (3) + Kitchen Appliances (4) = 12 points',
      baseQuantity: 12,
      wastagePercent: 0,
      finalQuantity: 12,
      quantityType: 'MEASURED',
      materialRate: 1350,
      labourRate: 550,
      equipmentRate: 50,
      subcontractRate: 0,
      unitCost: 1950,
      totalCost: 23400,
      markupPercent: 25,
      sellingRate: 2438,
      sellingAmount: 29256,
      rateSource: 'APPROVED_MASTER',
      rateStatus: 'APPROVED',
      sourceDocumentRef: 'Skyline_1402_Architectural_FloorPlan_RevB.pdf (Page 4)',
      assumptions: 'Sub-distribution board has sufficient spare ways.',
      isApprovedByEstimator: false
    },

    // Modular Kitchen
    {
      id: 'BOQ-010',
      boqRevisionId: rev0Id,
      itemCode: 'KIT-01',
      trade: 'MODULAR_KITCHEN',
      workPackage: 'Kitchen Carcass & Drawers',
      floor: '14th Floor',
      roomZone: 'Gourmet Modular Kitchen',
      description: 'Modular kitchen base and overhead storage carcass fabricated from 18mm BWP IS 710 Marine Grade calibrated plywood with soft-close tandem drawers.',
      specification: 'IS 710 Marine Plywood, 0.8mm internal off-white laminate, Hafele soft-close runners',
      brandGrade: 'Century Marine 710 + Hafele Matrix Box',
      inclusions: 'Cutlery tray, plain basket, thali basket, bottle pull-out, corner carousel',
      exclusions: 'Built-in appliances (Hob, Chimney, Oven)',
      unit: 'sq.ft',
      quantityFormula: 'Base units (14ft + 9ft - 2ft corner) * 2.75ft = 57.75 sq.ft; Overhead (14ft + 7ft) * 2.5ft = 52.5 sq.ft; Tall Unit = 15 sq.ft. Total = 125.25 sq.ft',
      baseQuantity: 125.25,
      wastagePercent: 5,
      finalQuantity: 131.51,
      quantityType: 'MEASURED',
      materialRate: 1250,
      labourRate: 350,
      equipmentRate: 50,
      subcontractRate: 0,
      unitCost: 1650,
      totalCost: 216991.5,
      markupPercent: 24.8,
      sellingRate: 2060,
      sellingAmount: 270910.6,
      rateSource: 'APPROVED_MASTER',
      rateStatus: 'APPROVED',
      sourceDocumentRef: 'Skyline_1402_Kitchen_Detailed_Layout.pdf',
      assumptions: 'Sink cabinet includes PVC drip tray and water barrier.',
      isApprovedByEstimator: false
    },
    {
      id: 'BOQ-011',
      boqRevisionId: rev0Id,
      itemCode: 'KIT-02',
      trade: 'MODULAR_KITCHEN',
      workPackage: 'Kitchen Shutters',
      floor: '14th Floor',
      roomZone: 'Gourmet Modular Kitchen',
      description: 'Seamless 1.5mm scratch-resistant high-gloss Acrylic front shutters on 18mm HDHMR board with zero-joint edge banding and concealed J-pull profiles.',
      specification: 'Senoplast Acrylic surface on Action TESA HDHMR board',
      brandGrade: 'Action TESA HDHMR + Rehau German Edge Banding',
      inclusions: '110 deg soft-close Hafele hinges, gas struts for lift-up overheads',
      exclusions: 'Glass profile display lights',
      unit: 'sq.ft',
      quantityFormula: 'Front shutter frontal area = 110 sq.ft',
      baseQuantity: 110,
      wastagePercent: 5,
      finalQuantity: 115.5,
      quantityType: 'MEASURED',
      materialRate: 650,
      labourRate: 180,
      equipmentRate: 30,
      subcontractRate: 0,
      unitCost: 860,
      totalCost: 99330,
      markupPercent: 25,
      sellingRate: 1075,
      sellingAmount: 124162.5,
      rateSource: 'APPROVED_MASTER',
      rateStatus: 'APPROVED',
      sourceDocumentRef: 'Client Brief (High-Gloss Champagne White finish)',
      assumptions: 'UV resistant acrylic with protective peel-off film during site handover.',
      isApprovedByEstimator: false
    },
    {
      id: 'BOQ-012',
      boqRevisionId: rev0Id,
      itemCode: 'KIT-03',
      trade: 'MODULAR_KITCHEN',
      workPackage: 'Countertop & Backsplash',
      floor: '14th Floor',
      roomZone: 'Gourmet Modular Kitchen',
      description: 'Supplying and installing 18mm Quartz engineered stone countertop with 40mm sandwich moulded edge, under-mount sink cutout, and 100mm border splash.',
      specification: 'Engineered Quartz slab, stain and acid resistant, zero porosity',
      brandGrade: 'KalingaStone White Terrazzo or Classic White',
      inclusions: 'Under-mount sink silicone seal, hob cutout with heat shield tape',
      exclusions: 'Plumbing fixtures (faucet & drain trap)',
      unit: 'sq.ft',
      quantityFormula: 'Length 21 ft * width 2.2 ft = 46.2 sq.ft + backsplash 15 sq.ft = 61.2 sq.ft',
      baseQuantity: 61.2,
      wastagePercent: 8,
      finalQuantity: 66.1,
      quantityType: 'MEASURED',
      materialRate: 380,
      labourRate: 140,
      equipmentRate: 30,
      subcontractRate: 0,
      unitCost: 550,
      totalCost: 36355,
      markupPercent: 21.8,
      sellingRate: 670,
      sellingAmount: 44287,
      rateSource: 'APPROVED_MASTER',
      rateStatus: 'APPROVED',
      sourceDocumentRef: 'Kitchen Detail Spec Sheet',
      assumptions: 'Seamless 45-degree mitered edge joint at corner.',
      isApprovedByEstimator: false
    },

    // Wardrobes & Storage
    {
      id: 'BOQ-013',
      boqRevisionId: rev0Id,
      itemCode: 'WRD-01',
      trade: 'WARDROBES_STORAGE',
      workPackage: 'Master Bedroom Wardrobe Carcass',
      floor: '14th Floor',
      roomZone: 'Master Bedroom Suite',
      description: 'Floor-to-ceiling built-in sliding wardrobe carcass in 18mm BWR commercial grade plywood with 1mm laminate internal lining and Hafele top-hung sliding hardware.',
      specification: 'IS 303 BWR plywood with Hafele In-Line soft-close sliding system',
      brandGrade: 'Century Pro BWR + Hafele Slido System',
      inclusions: 'Hanging rods, 4 soft-close internal lockable drawers, tie rack, loft compartments',
      exclusions: 'Interior sensor LED strip lighting',
      unit: 'sq.ft',
      length: 10,
      height: 9.5,
      quantityFormula: '10 ft width * 9.5 ft ceiling height = 95 sq.ft',
      baseQuantity: 95,
      wastagePercent: 5,
      finalQuantity: 99.75,
      quantityType: 'MEASURED',
      materialRate: 1100,
      labourRate: 320,
      equipmentRate: 40,
      subcontractRate: 0,
      unitCost: 1460,
      totalCost: 145635,
      markupPercent: 25,
      sellingRate: 1825,
      sellingAmount: 182043.75,
      rateSource: 'APPROVED_MASTER',
      rateStatus: 'APPROVED',
      sourceDocumentRef: 'Skyline_1402_Architectural_FloorPlan_RevB.pdf (Wardrobe Schedule)',
      assumptions: 'Clear internal wardrobe depth 24 inches for coat hangers.',
      isApprovedByEstimator: false
    },
    {
      id: 'BOQ-014',
      boqRevisionId: rev0Id,
      itemCode: 'WRD-02',
      trade: 'WARDROBES_STORAGE',
      workPackage: 'Master Wardrobe Veneer Shutters',
      floor: '14th Floor',
      roomZone: 'Master Bedroom Suite',
      description: 'Wardrobe sliding shutters finished in smoked American walnut natural architectural veneer pressed on 18mm HDHMR with satin PU Italian polish and full-height concealed aluminum edge handles.',
      specification: 'Natural 0.55mm bookmatched veneer with ICA Italian PU satin coat',
      brandGrade: 'Turakhia Natural Veneer + ICA Italian PU',
      inclusions: 'Aluminum stiffener rods to prevent warping, anti-dust seal brush',
      exclusions: 'Clear fluted glass shutter panels',
      unit: 'sq.ft',
      length: 10,
      height: 9.5,
      quantityFormula: '10 ft * 9.5 ft = 95 sq.ft',
      baseQuantity: 95,
      wastagePercent: 5,
      finalQuantity: 99.75,
      quantityType: 'MEASURED',
      materialRate: 580,
      labourRate: 220,
      equipmentRate: 30,
      subcontractRate: 0,
      unitCost: 830,
      totalCost: 82792.5,
      markupPercent: 25,
      sellingRate: 1038,
      sellingAmount: 103540.5,
      rateSource: 'APPROVED_MASTER',
      rateStatus: 'APPROVED',
      sourceDocumentRef: 'Client Preference Note (American Walnut finish)',
      assumptions: 'Veneer flitches to be physically inspected and approved before pressing.',
      isApprovedByEstimator: false
    },

    // Provisional Specialty Item (Demonstrating missing measurement & provisional rate handling!)
    {
      id: 'BOQ-015',
      boqRevisionId: rev0Id,
      itemCode: 'SPL-01',
      trade: 'CARPENTRY_JOINERY',
      workPackage: 'Feature Bed Wall Paneling',
      floor: '14th Floor',
      roomZone: 'Master Bedroom Suite',
      description: 'PROVISIONAL ITEM: Custom acoustic fluted wall paneling behind king bed with warm 3000K concealed LED channel step.',
      specification: 'Provisional specification pending client brand sign-off',
      brandGrade: 'Provisional - To be confirmed',
      inclusions: 'Acoustic substrate, fluted battens, primer coat',
      exclusions: 'Electric driver supply',
      unit: 'sq.ft',
      quantityFormula: 'Provisional allowance based on standard 10ft bed wall * 8ft height = 80 sq.ft',
      baseQuantity: 80,
      wastagePercent: 10,
      finalQuantity: 88,
      quantityType: 'PROVISIONAL_ALLOWANCE',
      materialRate: 280,
      labourRate: 90,
      equipmentRate: 15,
      subcontractRate: 0,
      unitCost: 385,
      totalCost: 33880,
      markupPercent: 20,
      sellingRate: 462,
      sellingAmount: 40656,
      rateSource: 'ILLUSTRATIVE_BENCHMARK',
      rateStatus: 'PROVISIONAL',
      sourceDocumentRef: 'Survey Note Item 6 (Client Verbal Request)',
      assumptions: 'PROVISIONAL ESTIMATE: Bed back height not finalized on architectural drawings; assumed 8.0 ft allowance.',
      uncertaintyFlags: 'Missing verified drawing elevation and client material sign-off.',
      isApprovedByEstimator: false
    }
  ];

  // Create Estimator Approved Baseline (Rev 1) with adjustments
  const demoBOQItemsRev1: BOQItem[] = demoBOQItemsRev0.map((item, idx) => ({
    ...item,
    id: `BOQ-REV1-${idx + 1}`,
    boqRevisionId: rev1Id,
    isApprovedByEstimator: true,
    reviewedBy: 'Rajesh Sharma (Lead Quantity Surveyor)'
  }));

  const rev0: BOQRevision = {
    id: rev0Id,
    projectId,
    revisionNumber: 0,
    revisionLabel: 'Rev 0 - AI Draft Takeoff',
    status: 'ESTIMATOR_REVIEW',
    items: demoBOQItemsRev0,
    createdAt: '2026-03-01T10:15:00Z',
    createdBy: 'AI Estimation Agent (Gemini-3.8-Flash)',
    missingDimensionAlerts: [
      'Master Bed Accent Wall elevation drawing missing confirmed height; provisional allowance of 8.0 ft height used.',
      'Balcony utility dado waterproofing height unconfirmed in structural brief; assumed standard 4.0 ft height.',
      'Unscaled moodboard photograph detected: Living room TV console unit requires dimensioned 2D CAD elevation before quantity takeoff.'
    ],
    missingRateAlerts: [
      'Item SPL-01 (Master Bed Fluted Paneling) has PROVISIONAL status with illustrative rate of ₹385/sq.ft. Final supplier quotation required before contract freeze.'
    ],
    notes: 'Generated via AI takeoff from Architectural Floor Plan Rev B and Site Survey Report.'
  };

  const rev1: BOQRevision = {
    id: rev1Id,
    projectId,
    revisionNumber: 1,
    revisionLabel: 'Rev 1 - Estimator Approved Baseline',
    status: 'APPROVED',
    items: demoBOQItemsRev1,
    createdAt: '2026-03-02T16:30:00Z',
    createdBy: 'Rajesh Sharma (Lead Quantity Surveyor)',
    approvedAt: '2026-03-02T18:00:00Z',
    approvedBy: 'Rajesh Sharma (Lead Quantity Surveyor)',
    missingDimensionAlerts: [],
    missingRateAlerts: [],
    notes: 'Quantities verified on site survey. Rate analysis confirmed against Master Library NCR Q1-2026.'
  };

  const sampleQuotation: CustomerQuotation = {
    id: 'QUOTE-SKYLINE-2026-001',
    quotationNumber: 'BS-QT-2026-1402',
    projectId,
    boqRevisionId: rev1Id,
    customerName: 'Mr. Vikram & Ananya Malhotra',
    projectTitle: '3BHK Turnkey Interior Execution - Skyline Residences Unit 1402',
    siteAddress: 'Flat 1402, Tower B, Skyline Residences, Sector 65, Gurugram, Haryana',
    selectedPackageTier: 'STANDARD',
    quotationDate: '2026-03-03',
    validityDays: 30,
    expiryDate: '2026-04-02',
    subtotalSellingAmount: 1305436.41,
    gstPercent: 18,
    gstAmount: 234978.55,
    totalQuotationAmount: 1540414.96,
    milestoneSchedule: [
      { id: 'MS-1', milestoneName: 'Project Mobilization & Order Sign-off', percentage: 10, amount: 154041.50, stageTrigger: 'Signing of turnkey contract & procurement release', status: 'PAID' },
      { id: 'MS-2', milestoneName: 'Completion of Demolition & Civil Waterproofing', percentage: 15, amount: 231062.24, stageTrigger: '72hr pond test passed & masonry complete', status: 'PENDING' },
      { id: 'MS-3', milestoneName: 'Concealed Electrical, Plumbing & False Ceiling Grid', percentage: 25, amount: 385103.74, stageTrigger: 'Pressure test sign-off & gypsum board installation', status: 'PENDING' },
      { id: 'MS-4', milestoneName: 'Modular Kitchen & Wardrobe Carcass Installation', percentage: 25, amount: 385103.74, stageTrigger: 'Carcass alignment & hardware fitting on site', status: 'PENDING' },
      { id: 'MS-5', milestoneName: 'Flooring, Tiling, Painting & Shutter Mounting', percentage: 15, amount: 231062.24, stageTrigger: 'Second coat painting & shutter alignment', status: 'PENDING' },
      { id: 'MS-6', milestoneName: 'Snag List Rectification, Deep Cleaning & Handover', percentage: 10, amount: 154041.50, stageTrigger: 'Final client walkthrough & key handover with warranty', status: 'PENDING' }
    ],
    inclusions: [
      'Complete civil demolition of identified partition wall with debris carting away to municipal yard.',
      'Two-coat elastomeric waterproofing in master bathroom with 72-hour pond testing warranty.',
      'Saint-Gobain Gyproc false ceiling in Living/Dining with perimeter LED light cove.',
      '1600x800mm High Gloss vitrified tile flooring in living area and AC4 German wooden flooring in master suite.',
      'Turnkey modular kitchen with 18mm BWP Marine Plywood carcass, Hafele soft-close runners, Senoplast acrylic shutters, and quartz countertop.',
      'Floor-to-ceiling sliding wardrobe in master bedroom with smoked American walnut veneer shutters and Italian PU finish.',
      'Entire apartment interior painting with Asian Paints Royale Luxury Emulsion.',
      'Dedicated project site engineer, weekly progress photo certification, and final machine deep cleaning.'
    ],
    exclusions: [
      'Supply of decorative chandeliers, hanging pendants, and loose portable furniture items.',
      'Supply of kitchen appliances (Built-in Hob, Chimney, Microwave, Refrigerator, Dishwasher).',
      'Civil modifications to building facade, external balcony structural railings, or structural columns/beams.',
      'Electricity and water charges for site execution to be provided free of cost by the Client at site tap.'
    ],
    termsAndConditions: [
      'Quotation validity is strictly 30 calendar days from the date of issuance.',
      'Delivery schedule is 75 working days from the date of site handover and receipt of initial mobilization advance.',
      'Any changes or additions to the agreed scope will be executed strictly via written and approved Variation Orders (VO).',
      'All civil and structural waterproofing carries a 5-Year Build Storys Comprehensive Warranty against leakage.',
      'Hardware and drawer systems carry manufacturer direct warranty (Hafele: 5-year mechanical warranty).'
    ],
    status: 'ACCEPTED'
  };

  return {
    id: projectId,
    projectCode: 'BS-2026-1402',
    title: 'Skyline Residences - Unit 1402 (3BHK Turnkey Interior)',
    clientName: 'Mr. Vikram & Ananya Malhotra',
    clientPhone: '+91 98102 44321',
    clientEmail: 'vikram.malhotra@skyline.org',
    projectType: 'RESIDENTIAL',
    projectScope: 'TURNKEY_INTERIORS',
    siteAddress: 'Flat 1402, Tower B, Skyline Residences, Golf Course Extension Road',
    city: 'Gurugram, NCR',
    stage: 'CUSTOMER_QUOTATION',
    carpetAreaSqFt: 1650,
    estimatedBudget: 2600000,
    createdAt: '2026-03-01T09:00:00Z',
    updatedAt: '2026-03-03T11:45:00Z',
    requirement: {
      id: 'REQ-1402',
      projectId,
      customerName: 'Mr. Vikram & Ananya Malhotra',
      customerPhone: '+91 98102 44321',
      customerEmail: 'vikram.malhotra@skyline.org',
      billingAddress: 'Flat 1402, Tower B, Skyline Residences, Sector 65, Gurugram, Haryana - 122018',
      projectSiteAddress: 'Flat 1402, Tower B, Skyline Residences, Sector 65, Gurugram, Haryana - 122018',
      city: 'Gurugram',
      projectType: 'RESIDENTIAL',
      projectScope: 'TURNKEY_INTERIORS',
      plotAreaSqFt: 0,
      builtUpAreaSqFt: 1980,
      carpetAreaSqFt: 1650,
      floorsCount: 1,
      rooms: [
        {
          id: 'ROOM-1',
          name: 'Living & Dining Lounge',
          zone: 'Living Zone',
          floor: '14th Floor',
          lengthFt: 24,
          widthFt: 14.5,
          heightFt: 9.5,
          carpetAreaSqFt: 348,
          perimeterFt: 77,
          wallAreaSqFt: 731.5,
          ceilingAreaSqFt: 348,
          existingCondition: 'Builder bare shell with uneven plaster',
          demolitionRequired: true,
          notes: 'Partition wall to study needs dismantling.'
        },
        {
          id: 'ROOM-2',
          name: 'Master Bedroom Suite',
          zone: 'Private Zone',
          floor: '14th Floor',
          lengthFt: 16,
          widthFt: 13,
          heightFt: 9.5,
          carpetAreaSqFt: 208,
          perimeterFt: 58,
          wallAreaSqFt: 551,
          ceilingAreaSqFt: 208,
          existingCondition: 'Bare concrete sub-floor',
          demolitionRequired: false,
          notes: 'Wooden flooring and 10ft sliding veneer wardrobe.'
        },
        {
          id: 'ROOM-3',
          name: 'Master Ensuite Bathroom',
          zone: 'Wet Zone',
          floor: '14th Floor',
          lengthFt: 8,
          widthFt: 6.5,
          heightFt: 8.5,
          carpetAreaSqFt: 52,
          perimeterFt: 29,
          wallAreaSqFt: 246.5,
          ceilingAreaSqFt: 52,
          existingCondition: 'Sunken slab with builder core pipes',
          demolitionRequired: false,
          notes: 'Complete elastomeric waterproofing and 72hr pond testing.'
        },
        {
          id: 'ROOM-4',
          name: 'Gourmet Modular Kitchen',
          zone: 'Utility & Cooking',
          floor: '14th Floor',
          lengthFt: 14,
          widthFt: 9,
          heightFt: 9.5,
          carpetAreaSqFt: 126,
          perimeterFt: 46,
          wallAreaSqFt: 437,
          ceilingAreaSqFt: 126,
          existingCondition: 'Bare brick wall without dado',
          demolitionRequired: false,
          notes: 'BWP Marine Ply, acrylic shutters, quartz counter, Hafele tandem drawers.'
        },
        {
          id: 'ROOM-5',
          name: 'Guest Bedroom',
          zone: 'Private Zone',
          floor: '14th Floor',
          lengthFt: 13.5,
          widthFt: 12,
          heightFt: 9.5,
          carpetAreaSqFt: 162,
          perimeterFt: 51,
          wallAreaSqFt: 484.5,
          ceilingAreaSqFt: 162,
          existingCondition: 'Bare shell',
          demolitionRequired: false,
          notes: 'Wardrobe with laminates, Royale emulsion.'
        },
        {
          id: 'ROOM-6',
          name: 'Kids Bedroom / Study',
          zone: 'Private Zone',
          floor: '14th Floor',
          lengthFt: 12,
          widthFt: 11.5,
          heightFt: 9.5,
          carpetAreaSqFt: 138,
          perimeterFt: 47,
          wallAreaSqFt: 446.5,
          ceilingAreaSqFt: 138,
          existingCondition: 'Bare shell',
          demolitionRequired: false,
          notes: 'Study desk joinery, storage units.'
        }
      ],
      preferredDesignStyle: 'Warm Contemporary Minimalism with Clean Architectural Lines and Natural Smoked Oak Veneer',
      materialsBrandsPreferences: 'Kajaria Vitrified Tiles, Saint-Gobain Gyproc, Asian Paints Royale Luxury Emulsion, Hafele hardware, Century 710 Marine Plywood, KalingaStone Quartz',
      civilRequirements: 'Demolition of non-load bearing wall between dining and study room; make good edges with 12mm plaster and wire mesh.',
      electricalRequirements: '145 concealed points, Legrand Arteor white modular switches, dedicated power home-runs for 5 split ACs and heavy kitchen appliances.',
      plumbingSanitaryRequirements: 'CPVC hot and cold Concealed Astral pipes with pressure testing; Grohe/Kohler diverters.',
      hvacRequirements: 'Concealed copper piping for VRV / Inverter Split AC units in all 3 bedrooms and living room.',
      joineryKitchenPreferences: 'German soft-close tandem boxes, Senoplast high-gloss acrylic shutters, 18mm BWP marine plywood carcass.',
      customerBudgetMin: 2200000,
      customerBudgetMax: 2700000,
      targetCompletionDate: '2026-05-30',
      exclusionsCustomerSupplied: 'Client will supply chandeliers, refrigerator, microwave, and loose sofa sets.',
      siteAccessConstraints: 'Society working hours strictly 9:30 AM to 6:00 PM; no noisy work on Sundays; dedicated freight lift pass required.',
      surveyNotes: 'Ceiling height clear at 9.5 ft. Sub-slab in bathrooms clean. Balcony floor level has 50mm drop suitable for anti-skid tiles.',
      rawBriefHindiEnglish: 'Living room me Kajaria ki 1600x800 high gloss vitrified tiles chahiye Italian marble finish wali. Dining aur study ke beech ki partition wall demolish karni hai. Pure apartment me Saint Gobain gypsum ceiling with indirect LED cove lights. Kitchen me 100% waterproof BWP marine ply carcass with Senoplast acrylic shutters and white quartz countertop. Master bedroom me 10x8 sliding wardrobe with natural smoked walnut veneer and Italian PU polish. Master bathroom me 72 hours pond test ke sath Dr. Fixit waterproofing chahiye. Budget range 24-27 Lakhs.',
      documents: [
        {
          id: 'DOC-01',
          filename: 'Skyline_1402_Architectural_FloorPlan_RevB.pdf',
          fileType: 'application/pdf',
          sizeKb: 4820,
          uploadedAt: '2026-03-01T09:30:00Z',
          uploadedBy: 'Client Portal (Vikram Malhotra)',
          documentType: 'FLOOR_PLAN_DRAWING',
          version: 'Rev B',
          scaleConfirmed: true,
          scaleRatio: '1:100',
          notes: 'Scale confirmed and dimension lines verified by QS.'
        },
        {
          id: 'DOC-02',
          filename: 'Site_Survey_Civil_Structural_Inspection.pdf',
          fileType: 'application/pdf',
          sizeKb: 3150,
          uploadedAt: '2026-03-01T11:00:00Z',
          uploadedBy: 'Ramesh Verma (Site Engineer)',
          documentType: 'SITE_SURVEY_PHOTO',
          version: 'v1.0',
          scaleConfirmed: true,
          notes: 'Photographic survey with moisture meter test readings.'
        }
      ],
      updatedAt: '2026-03-01T11:30:00Z'
    },
    activeRevisionId: rev1Id,
    revisions: [rev0, rev1],
    quotation: sampleQuotation
  };
}

export function getAlternativePackages(baseCost: number): AlternativePackageOption[] {
  // Deterministic 3 alternatives with distinct specifications
  return [
    {
      tier: 'ECONOMY',
      title: 'Essential Living Package',
      badge: 'Optimized Value',
      specificationsSummary: 'Premium laminate finishes, 600x600 GVT tiles, MR grade commercial plywood, Asian Paints Premium Emulsion.',
      materialsHighlights: [
        'Kajaria 600x600mm Double Charged Vitrified Tiles',
        '18mm MR Grade Commercial Plywood with 1mm Laminate Shutters',
        'Saint-Gobain Gyproc Basic Gypsum False Ceiling',
        'Asian Paints Tractor Emulsion / Premium Emulsion',
        'Anchor Roma Modular Switches'
      ],
      totalDirectCost: Math.round(baseCost * 0.76),
      totalSellingPrice: Math.round(baseCost * 0.76 * 1.25),
      marginPercent: 20.0,
      timelineWeeks: 8,
      warrantyPeriod: '2 Years Comprehensive',
      assumptions: [
        'Standard laminate finishes without veneer or PU',
        '600x600mm tiles instead of 1600x800mm large slabs',
        'Standard channel runners instead of tandem boxes'
      ]
    },
    {
      tier: 'STANDARD',
      title: 'Signature Architectural Package',
      badge: 'Recommended Turnkey',
      specificationsSummary: '1600x800mm GVT tiles, BWP 710 Marine Ply Kitchen, German soft-close tandem boxes, Senoplast Acrylic shutters, Royale Luxury Emulsion, Hafele hardware.',
      materialsHighlights: [
        'Kajaria 1600x800mm Large Format Glazed Vitrified Tiles',
        'IS 710 Marine Plywood kitchen carcass with Hafele Matrix Box',
        'Senoplast German high-gloss acrylic shutters',
        'Smoked American Walnut natural veneer for master wardrobe with PU polish',
        'Saint-Gobain Gypsteel Ultra framing with architectural LED cove step',
        'Asian Paints Royale Luxury Sheen Emulsion',
        'Legrand Arteor modular switches & Schneider MCBs'
      ],
      totalDirectCost: Math.round(baseCost),
      totalSellingPrice: Math.round(baseCost * 1.26),
      marginPercent: 20.6,
      timelineWeeks: 10,
      warrantyPeriod: '5 Years Comprehensive (Waterproofing & Carcass)',
      assumptions: [
        'High-gloss acrylic kitchen shutters with quartz countertop',
        'Natural architectural veneer on master wardrobe with Italian PU coat',
        'Two coats Dr. Fixit Fastflex with 72hr pond test'
      ]
    },
    {
      tier: 'PREMIUM',
      title: 'Opulent Bespoke Luxury Package',
      badge: 'Ultra Luxury',
      specificationsSummary: 'Imported Italian Marble (Bottochino / Statuario) with mirror polish, custom PU lacquered fluted carpentry, full smart home lighting automation, Daikin VRV integration.',
      materialsHighlights: [
        'First Quality Imported Italian Statuario/Bottochino Marble in Living/Dining',
        'Custom German Blum Aventos servo-drive motorized kitchen cabinets',
        'Full bespoke fluted wall paneling with brushed brass metal profiles',
        'Italian ICA polyester high-gloss mirror finish on joinery',
        'Full KNX / Lutron smart lighting and HVAC automation integration',
        'Kohler Veil wall-hung smart bidet toilets & Hansgrohe thermostatic showers'
      ],
      totalDirectCost: Math.round(baseCost * 1.55),
      totalSellingPrice: Math.round(baseCost * 1.55 * 1.32),
      marginPercent: 24.2,
      timelineWeeks: 14,
      warrantyPeriod: '10 Years Complete Warranty + 3 Years Annual Maintenance (AMC)',
      assumptions: [
        'Imported marble slab dry-lay preview and diamond pad crystal polishing',
        'Fully motorized touch-to-open drawer hardware',
        'Architectural trimless magnetic track lighting fixtures included'
      ]
    }
  ];
}

export function getValueEngineeringOptions(): ValueEngineeringOption[] {
  return [
    {
      id: 'VE-001',
      trade: 'MODULAR_KITCHEN',
      roomZone: 'Gourmet Modular Kitchen',
      originalSpec: 'Imported Quartz 18mm Countertop (KalingaStone @ ₹670/sq.ft)',
      proposedAlternative: 'High-density Polished Jet Black Granite with 40mm sandwich bevel edge (@ ₹420/sq.ft)',
      costSaving: 11500,
      sellingReduction: 16525,
      clientQualityImpact: 'Zero functional durability loss; excellent heat and scratch resistance with dark natural stone look.',
      isAccepted: false
    },
    {
      id: 'VE-002',
      trade: 'WARDROBES_STORAGE',
      roomZone: 'Master Bedroom Suite',
      originalSpec: 'Smoked American Walnut Natural Architectural Veneer with Italian PU Polish (@ ₹1038/sq.ft)',
      proposedAlternative: 'Ultra-Matte Anti-Fingerprint Synchronized Textured Laminate (Merino Tufo / Greenlam @ ₹550/sq.ft)',
      costSaving: 27930,
      sellingReduction: 48678,
      clientQualityImpact: 'Slight reduction in organic grain depth, but significantly higher scratch resistance and zero maintenance polishing required.',
      isAccepted: false
    },
    {
      id: 'VE-003',
      trade: 'FALSE_CEILINGS',
      roomZone: 'Living & Dining Lounge',
      originalSpec: 'Continuous dual-layer perimeter gypsum LED light cove (@ ₹150/r.ft)',
      proposedAlternative: 'Single step architectural shadow recess with surface slimline magnetic profile channel',
      costSaving: 3234,
      sellingReduction: 4042,
      clientQualityImpact: 'Modern minimalist European clean aesthetic, eliminates dust collection shelf.',
      isAccepted: false
    }
  ];
}
