import React,{useState,useEffect} from 'react';
import {ProjectRecord,UserSession,CostBudgetSummary} from '../types/erp';
import {ERP_MODULES_REGISTRY} from '../data/modulesRegistry';
interface MandatoryReportsHubViewProps {project:ProjectRecord;currentUser:UserSession;budgetSummary:CostBudgetSummary|null;onNavigateTab?:(tab:string)=>void;onOpenAIWorkspace?:()=>void;}
const modules=['crm','contacts','drawings','materials','contracts','variations','schedule','site_execution','procurement','inventory','contractors','snags','handover','portal','finance','billing','documents','resources','assets','compliance'];
const label=(id:string)=>ERP_MODULES_REGISTRY.find(m=>m.tabKey===id)?.name || id;
export function MandatoryReportsHubView({project,budgetSummary,onNavigateTab}:MandatoryReportsHubViewProps){
 const [report,setReport]=useState('boq'),[records,setRecords]=useState<any[]>([]),[error,setError]=useState(''),[query,setQuery]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{let cancelled=false;setError('');setQuery('');setRecords([]);
 if(!modules.includes(report))return;
 setLoading(true);fetch('/api/operations/'+encodeURIComponent(project.id)+'/'+report).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);if(!cancelled)setRecords(d);}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[project.id,report]);
 const revision=project.revisions.find(r=>r.id===project.activeRevisionId)||project.revisions[0];
 let rows:any[]= report==='boq'?(revision?.items||[]).map(i=>({'Item code':i.itemCode,Description:i.description,Trade:i.trade,Zone:i.roomZone,Unit:i.unit,Quantity:i.finalQuantity,'Unit cost INR':i.unitCost,'Cost INR':i.totalCost,'Selling INR':i.sellingAmount,'Rate status':i.rateStatus})):report==='budget'?Object.entries(budgetSummary||{}).filter(([,v])=>typeof v==='number').map(([k,v])=>({Metric:k.replace(/([A-Z])/g,' $1'),Value:v})):records.map(({id,...rest})=>rest);
 rows=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())&&(!from||!r.updatedAt||r.updatedAt.slice(0,10)>=from)&&(!to||!r.updatedAt||r.updatedAt.slice(0,10)<=to));
 const cols=Array.from(new Set(rows.flatMap(r=>Object.keys(r))));
 const exportCSV=()=>{const cell=(v:any)=>'"'+String(v??'').replace(/^[=+@-]/,"'").replaceAll('"','""')+'"';const csv=[cols,...rows.map(r=>cols.map(k=>r[k]))].map(r=>r.map(cell).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download=project.projectCode+'-'+report+'.csv';a.click();URL.revokeObjectURL(a.href);};
 const sum=(key:string)=>rows.reduce((t,r)=>t+(Number(r[key])||0),0);
 return <div className="bg-white border border-slate-200 rounded-xl p-5 space-y-4">
 <div className="flex flex-wrap items-center gap-3"><div className="mr-auto"><h1 className="text-xl font-bold">Project reports</h1><p className="text-sm text-slate-500">{project.projectCode} · {project.title}</p></div><button className="border px-3 py-2 rounded" onClick={exportCSV}>Export CSV</button><button className="border px-3 py-2 rounded" onClick={()=>window.print()}>Print / Save PDF</button></div>
 <div className="flex flex-wrap gap-3"><label className="text-xs">Report<select aria-label="Report" value={report} onChange={e=>setReport(e.target.value)} className="block border rounded p-2"><option value="boq">BOQ detail & cost</option><option value="budget">Estimated project budget</option>{modules.map(id=><option value={id} key={id}>{label(id)} register</option>)}</select></label><label className="text-xs">Search<input value={query} onChange={e=>setQuery(e.target.value)} className="block border rounded p-2"/></label><label className="text-xs">Updated from<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="block border rounded p-2"/></label><label className="text-xs">Updated to<input type="date" value={to} onChange={e=>setTo(e.target.value)} className="block border rounded p-2"/></label></div>
 {error&&<p role="alert" className="text-rose-700">{error}</p>}
 <p className="text-sm text-slate-600">{rows.length} records · {report==='boq'?'Selected estimating revision; costs remain estimates until verified.':report==='budget'?'Calculated estimating budget.':'Saved operational records for this job.'}</p>
 {report==='billing'&&<div className="bg-slate-50 rounded p-3 text-sm">Invoiced: ₹{(sum('Taxable amount INR')+sum('GST amount INR')).toLocaleString('en-IN')} · Received: ₹{sum('Paid amount INR').toLocaleString('en-IN')} · Outstanding: ₹{(sum('Taxable amount INR')+sum('GST amount INR')-sum('Paid amount INR')).toLocaleString('en-IN')}</div>}
 {report==='finance'&&<div className="bg-slate-50 rounded p-3 text-sm">Debit: ₹{sum('Debit INR').toLocaleString('en-IN')} · Credit: ₹{sum('Credit INR').toLocaleString('en-IN')} · Difference: ₹{(sum('Debit INR')-sum('Credit INR')).toLocaleString('en-IN')}</div>}
 {loading?<p>Loading report…</p>:<div className="overflow-x-auto"><table className="w-full text-xs text-left"><thead><tr>{cols.map(k=><th key={k} className="p-3 border-b whitespace-nowrap bg-slate-50">{k}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{cols.map(k=><td key={k} className="p-3 border-b min-w-28 max-w-80 break-words">{typeof r[k]==='number'?r[k].toLocaleString('en-IN'):String(r[k]??'—')}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="text-center py-12 text-slate-500">No matching saved data. Add records in the corresponding module.</p>}</div>}
 {modules.includes(report)&&<button className="text-blue-700 underline text-sm" onClick={()=>onNavigateTab?.(report)}>Open {label(report)}</button>}
 </div>;
}
