import React, {useState,useEffect} from 'react';
const specs:Record<string,string[]> = {
 crm:['Contact email','Contact phone','Source','Service required','Budget INR','Next follow-up'],contacts:['Email','Phone','Company','Billing address','GSTIN','Site address'],
 drawings:['Drawing number','Discipline','Revision','Designer','File URL','Approval date'],materials:['Material code','Brand','Finish','Unit','Quantity','Rate INR','Supplier'],
 contracts:['Contract number','Counterparty','Contract value INR','Start date','End date','Retention percent','Payment terms'],variations:['Variation number','Reason','Cost impact INR','Days impact','Approval reference'],
 schedule:['WBS code','Owner','Start date','Due date','Progress percent','Dependency'],site_execution:['Report date','Supervisor','Work area','Labour count','Hours','Progress percent','Photo URL'],
 procurement:['PO number','Vendor','Item description','Unit','Quantity','Unit rate INR','Expected date','Delivery address'],inventory:['Item code','Warehouse','Movement type','Quantity','Unit','Reference document','Movement date'],
 contractors:['Contractor','Trade','Phone','Work order','Agreed amount INR','Certified amount INR','Retention INR'],snags:['Location','Category','Severity','Assigned to','Due date','Resolution','Photo URL'],
 handover:['Certificate number','Handover date','Client representative','Warranty start date','Warranty end date','Retention INR','Document URL'],portal:['Client','Request type','Submitted date','Approval reference','Document URL'],
 finance:['Voucher number','Voucher date','Account','Party','Debit INR','Credit INR','Reference'],billing:['Invoice number','Invoice date','Customer','Milestone','Taxable amount INR','GST amount INR','Paid amount INR','Due date'],
 documents:['Document number','Category','Version','Owner','File URL','Review date'],resources:['Resource name','Role','Phone','Assigned activity','Hours','Rate INR'],assets:['Asset code','Asset name','Location','Custodian','Purchase date','Value INR','Service due date'],compliance:['Requirement','Authority','Reference number','Responsible person','Due date','Certificate URL']
};
export function OperationalRegister({projectId,moduleId,title}:{projectId:string;moduleId:string;title:string}) {
 const [records,setRecords]=useState<any[]>([]),[draft,setDraft]=useState<any|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const url='/api/operations/'+encodeURIComponent(projectId)+'/'+moduleId;
 const fields=specs[moduleId] || ['Owner','Due date','Reference'];
 const load=async()=>{setLoading(true);try{const r=await fetch(url);const d=await r.json();if(!r.ok)throw new Error(d.error);setRecords(d);setError('');}catch(e:any){setError(e.message);}finally{setLoading(false);}};
 useEffect(()=>{setRecords([]);setDraft(null);setQuery('');load();},[url]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const d=await r.json();if(!r.ok)throw new Error(d.error);setDraft(null);await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const exportCSV=()=>{const cols=['title','status',...fields,'notes'];const cell=(v:any)=>'"'+String(v??'').replace(/^[=+@-]/,"'").replaceAll('"','""')+'"';const data=[cols,...records.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())).map(r=>cols.map(k=>r[k]))].map(r=>r.map(cell).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+data],{type:'text/csv;charset=utf-8'}));a.download=moduleId+'-register.csv';a.click();URL.revokeObjectURL(a.href);};
 return <section className="bg-white border border-slate-200 rounded-xl p-4 space-y-4">
 <div className="flex flex-wrap gap-2 items-center"><h2 className="font-bold mr-auto">{title} · {records.length} records</h2><button onClick={load} className="border rounded px-3 py-2 text-xs">Refresh</button><button onClick={exportCSV} className="border rounded px-3 py-2 text-xs">Export CSV</button><button disabled={loading} onClick={()=>setDraft({title:'',status:'Draft',notes:''})} className="bg-slate-900 text-white rounded px-3 py-2 text-xs">New record</button></div>
 {error && <p role="alert" className="bg-rose-50 text-rose-800 p-3 rounded">{error}</p>}
 <input aria-label="Search register" placeholder="Search records…" value={query} onChange={e=>setQuery(e.target.value)} className="border rounded-lg p-2 w-full text-sm"/>
 {loading?<p>Loading records…</p>:<div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr>{['Title','Status',...fields.slice(0,4),'Actions'].map(f=><th className="p-3 whitespace-nowrap border-b" key={f}>{f}</th>)}</tr></thead><tbody>{records.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())).map(r=><tr key={r.id}>{['title','status',...fields.slice(0,4)].map(f=><td className="p-3 border-b max-w-64 break-words" key={f}>{String(r[f]??'—')}</td>)}<td className="p-3 border-b"><button className="underline mr-3" onClick={()=>setDraft({...r})}>Edit</button><button className="text-rose-700 underline" onClick={async()=>{if(!confirm('Delete this record permanently?'))return;const response=await fetch(url+'/'+r.id,{method:'DELETE'}).catch(()=>null);if(!response){setError('Could not connect. Please retry.');return;}const d=await response.json();if(!response.ok)setError(d.error);else load();}}>Delete</button></td></tr>)}</tbody></table>{records.length===0&&<p className="py-10 text-center text-slate-500">No records for this project yet. Create the first record to begin.</p>}</div>}
 {draft&&<div role="dialog" aria-modal="true" aria-label="Operational record" className="fixed inset-0 z-[100] bg-slate-900/50 p-4 flex items-start sm:items-center justify-center overflow-y-auto"><form onSubmit={save} className="bg-white rounded-xl p-5 w-full max-w-3xl max-h-[90dvh] overflow-y-auto space-y-4"><div className="flex items-center justify-between"><h3 className="font-bold">{draft.id?'Edit':'New'} {title} record</h3><button type="button" aria-label="Close record" onClick={()=>setDraft(null)}>✕</button></div>{error&&<p role="alert" className="text-rose-700">{error}</p>}<label className="block text-xs">Title *<input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} className="block w-full border rounded p-2 mt-1"/></label><label className="block text-xs">Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})} className="block w-full border rounded p-2 mt-1">{['Draft','Open','In Progress','Pending Approval','Approved','Completed','Cancelled'].map(v=><option key={v}>{v}</option>)}</select></label><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{fields.map(f=><label key={f} className="block text-xs">{f}<input type={f.endsWith('date')?'date':/INR|Quantity|percent|Hours|count|impact$/.test(f)?'number':f.endsWith('URL')?'url':'text'} step="any" value={draft[f]??''} onChange={e=>setDraft({...draft,[f]:e.target.value})} className="block w-full border rounded p-2 mt-1"/></label>)}</div><label className="block text-xs">Notes<textarea value={draft.notes||''} onChange={e=>setDraft({...draft,notes:e.target.value})} className="block w-full border rounded p-2 mt-1"/></label><div className="flex justify-end gap-2"><button type="button" className="border rounded px-4 py-2" onClick={()=>setDraft(null)}>Cancel</button><button disabled={busy} className="bg-slate-900 text-white rounded px-4 py-2">{busy?'Saving…':'Save & close'}</button></div></form></div>}
 </section>;
}
